### ISSUE TITLE
Adding a Rust implementation

### ISSUE THREAD

**Issue by darleybarreto** [paugier/nbabel#3]
Hi Mr. Augier, would you be interested in add a Rust implementation? If so, I could make a PR with [mine](https://github.com/darleybarreto/nbabel-nbody), or you could directly past inside your repo, whatever works best for you. Benchmarking with ` data/input128`, PyPy's execution of [purepy.py](https://github.com/paugier/nbabel/blob/master/py/bench_purepy.py) gave 4.9s and mine's gave between 0.6~0.65s.

**Comment by paugier** [comment]
Yes, I would really be interested in adding a Rust implementation! It seems to be as fast as expected! Could you please submit a PR?
